### ISSUE TITLE
This image failed to load

### ISSUE THREAD

**Issue by Marijnk7** [hooram/ownphotos-backend#66] opened 2019-01-30 19:36 UTC
Hi,

## Setup
I tried to setup Ownphotos with docker-compose on my Ubuntu 18.04 VPS with a mounted 2TB disk.

## Problem
The setup seems to work, i can also scan my nextcloud account, and the recognition, people, etc seems to work. Except that i can't view any images.

## Fix
So how can i fix this, is my configuration incorrectly or is there something else?

## docker-compose.yml
`version: '2'

services:

  proxy:
    image: guysoft/ownphotos-proxy
    tty: true
    container_name: ownphotos-proxy
    restart: always
    links:
      - "backend:backend"
      - "frontend:frontend"
    ports:
      - "3000:80"
      
  ownphotos-db:
    image: postgres
    container_name: ownphotos-db
    restart: always
    environment:
    # This db password is internal, you can change it if you want, but also change it in ownphotos-backend container
      - POSTGRES_PASSWORD=--secret--
      - POSTGRES_DB=ownphotos
    volumes:
      - ownphotos-data:/var/lib/postgresql/data

  frontend:
    container_name: ownphotos-frontend
    image: guysoft/ownphotos-frontend:dev
    tty: true
    environment:
       # This is the path to the backend host public facing. if your website is ownphotos.org then this should be "ownphotos.org".
       # Default here is assuming you are running on localhost on port 3000 as given in ownphotos-proxy service
       #- BACKEND_HOST=localhost:3000
       - BACKEND_HOST=--secret--
    links:
      - "backend:backend"

  backend:
    image: hooram/ownphotos:dev
    # For development uncomment this and comment the image name above
    #build: .
    container_name: ownphotos-backend
    volumes:
      # Your photos go here
      - /mnt/bigstorage/ownphotos/data:/data 
      - media:/code/media
    environment:
      - SECRET_KEY=--secret--
      # This is backend host from within the service, you dont need to change this
      - BACKEND_HOST=backend
      - ADMIN_EMAIL=--secret--
      - ADMIN_USERNAME=admin
      # Change your admin password!
      - ADMIN_PASSWORD=--secret--
      - DEBUG=false
      - DB_BACKEND=postgresql
      - DB_NAME=ownphotos
      - DB_USER=postgres
      # This db password is internal, you can change it if you want, but also change it in ownphotos-db container
      - DB_PASS=--secret--
      - DB_HOST=ownphotos-db
      - DB_PORT=5432
      - REDIS_HOST=ownphotos-redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=--secret--
    links:
      - "ownphotos-db:ownphotos-db"
      - "ownphotos-redis:ownphotos-redis"
  
  ownphotos-redis:
    image: redis
    container_name: ownphotos-redis

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: ownphotos-adminer
    links:
      - "ownphotos-db:db"

volumes:
  ownphotos-data:
  media:
`
## NGINX conf file
`server {
    # the port your site will be served on
    # the domain name it will serve for
    server_name --secret--;   # substitute by your FQDN and machine's IP address
    charset     utf-8;

    #Max upload size
    client_max_body_size 75M;   # adjust to taste

    # Django media
    location /media  {
        internal;
        alias /code/media;      # your Django project's media files
    }

    # Finally, send all non-media requests to the Django server.
    location / {

	add_header 'Access-Control-Allow-Origin' 'https://--secret--';
    add_header 'Access-Control-Allow_Credentials' 'true';
    add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
    add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';

        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/--secret--/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/--secret--/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = --secret--) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen      80;
    server_name --secret--;
    return 404; # managed by Certbot

}`

**Comment by guysoft** [comment] 2019-01-31 13:15
Which image is "this" image?
Do you mean your docker image isn't working?
Or images as in pictures in the system?

If you are using an nginx cerbot configuration I recommend using https://github.com/jwilder/nginx-proxy

**Comment by Marijnk7** [comment] 2019-01-31 18:47
Ahh sorry, with ‘this image’ i mean a picture. My pictures wont load.

**Comment by guysoft** [comment] 2019-02-03 09:42
Try clearing all your containers with their volumes and making sure its up to date.

1. 
```
sudo docker-compose stop
```


2. 
```
sudo docker-compose rm -f
```

3. 
```
sudo docker volume prune
```

4. 
```
sudo docker-compose pull
sudo docker-compose up -d
```

**Comment by hooram** [comment] 2019-02-03 09:45
Also make sure to link /code/protected_media in the container to somewhere on your file system (see docker-compse file), or all the media files will be lost upon container restart

**Comment by Marijnk7** [comment] 2019-02-03 13:21
Thank you for your answer. 

I don't precisely understand what you mean with linking /code/protected_media. in the docker-compose file there is nothing said about that. 

I changed - media:/code/media
to - /mnt/bigstorage/ownphotos/media:/code/media

Also if i look into the volume folders there is no data inside of there.
I removed the volume folders and when i restart the folders are re-created.

**Comment by guysoft** [comment] 2019-02-04 13:50
@mithek
1. Did you try the steps I provided above?
2. Does it work without your change?

**Comment by Marijnk7** [comment] 2019-02-04 18:37
@guysoft hey, thanks again for your answer.

Yes, i followed the steps above without my changes.
Except for linking  /code/protected_medie
I can't find any clues what to do for that.

**Comment by Marijnk7** [comment] 2019-02-04 19:43
I have some more information. If i look into the logs it often says: "photo not added to album place"
Also at the end it says: "{'new_photo_count': 0, 'status': True}" 

The dashboard says i have 24 photos.

![screenshot 2019-02-04 at 20 40 17](https://user-images.githubusercontent.com/6682832/52232650-5c101a80-28bd-11e9-8312-c52b5319ccd7.png)

[ownphotos-logs.log](https://github.com/hooram/ownphotos/files/2829584/ownphotos-logs.log)

**Comment by hooram** [comment] 2019-02-08 03:08
Hi @mithek, the "photo not added to album place" message is displayed in the log when it could not geolocate the photo. It's probably the case that your photos don't have any GPS information. Regarding the  dashboard saying that you have 24 photos: do you have more photos that should've been imported? Are you able to browse them? Or does it show a broken image where they should be?

**Comment by wtrdk** [comment] 2019-02-12 12:35
I also encounter the same problem as @mithek. After the container is restarted all thumbnails disappeared and end up in an 404 error.
I'changed my the media line docker-compose.yml to this:
```
- $HOME/.ownphotos_cache/:/code/media
```
I've followed the steps in https://github.com/hooram/ownphotos/issues/66#issuecomment-460037225 and scanned all the pictures again succesfully.

The directory .ownphotos_cache is writable, but there's nothing stored in that directory. After restarting the container the pictures are again not available in ownphotos.

**Comment by guysoft** [comment] 2019-02-12 14:01
Related to #71

@hooram Can you please say what the desired behaviour is?
I can't find any reference in the code to``.ownphotos_cache`` or ``/protected_media``

**Comment by hooram** [comment] 2019-02-12 14:32
@wtrdk, the line should be `- $HOME/.ownphotos_cache/:/code/protected_media`. @guysoft, the reference to this in the code is in https://github.com/hooram/ownphotos/blob/dev/ownphotos/settings.py#L260. In the Photo model https://github.com/hooram/ownphotos/blob/dev/api/models.py#L99 from line 99 to line 111, when the different sizes of thumbnails and the fullsize image of the photos are saved (in _generate_thumbnail and _save_image_to_db of the Photo model), the image files are saved to the `upload_to` subfolders as specified in the thumbnail fields (line 99~111).

The take home message is that https://github.com/hooram/ownphotos/blob/dev/ownphotos/settings.py#L260 specifies where the thumbnails (full size copies of originals, cropped faces, etc.) are saved, and it is located in `protected_media`, not `media`. So if you want these to persist between container restarts (which you probably do, otherwise they would 404 after container restart), then in line 46 of docker-compse.yml you should add 


`- /path/to/save/images/created/by/ownphotos:/code/protected_media`

 I hope this helps.

**Comment by guysoft** [comment] 2019-02-12 14:42
ok, just making sure we dont need to keep between container restarts also ``/code/media``?
Because #71 is a switch, not an addition.|

Once this is confirmed we can close this issue :)

**Comment by wtrdk** [comment] 2019-02-12 14:45
I've immediately tested it, and my ```.ownphotos_cache``` directory is being filled:
```
[wtrdk@wtrdk-server ~/.ownphotos_cache]$ ls -l
total 40K
drwxr-xr-x 2 root root 4.0K Feb 12 15:42 faces
drwxr-xr-x 2 root root 4.0K Feb 12 15:43 photos
drwxr-xr-x 2 root root 4.0K Feb 12 15:43 square_thumbnails
drwxr-xr-x 2 root root 4.0K Feb 12 15:43 square_thumbnails_big
drwxr-xr-x 2 root root 4.0K Feb 12 15:43 square_thumbnails_small
drwxr-xr-x 2 root root 4.0K Feb 12 15:43 square_thumbnails_tiny
drwxr-xr-x 2 root root 4.0K Feb 12 15:43 thumbnails
drwxr-xr-x 2 root root 4.0K Feb 12 15:43 thumbnails_big
drwxr-xr-x 2 root root 4.0K Feb 12 15:43 thumbnails_small
drwxr-xr-x 2 root root 4.0K Feb 12 15:43 thumbnails_tiny
```

I'm going to test this somewhat, but it seems to work now!

**Comment by hooram** [comment] 2019-02-12 14:46
Right. I meant to replace the line. Thanks for the double ckeck :grin:

**Comment by Marijnk7** [comment] 2019-02-12 18:49
Awesome it fixed it for me!

You guys @hooram & @guysoft  do fantastic work!

**Comment by guysoft** [comment] 2019-02-13 09:01
Ok, issue resolved :)

**Closed as completed by guysoft** 2019-02-13 09:01 UTC
